//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Greet", ReplyAction="http://tempuri.org/IService1/GreetResponse")]
        string Greet(string s1, string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Greet", ReplyAction="http://tempuri.org/IService1/GreetResponse")]
        System.Threading.Tasks.Task<string> GreetAsync(string s1, string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MilesToKM", ReplyAction="http://tempuri.org/IService1/MilesToKMResponse")]
        double MilesToKM(double d1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MilesToKM", ReplyAction="http://tempuri.org/IService1/MilesToKMResponse")]
        System.Threading.Tasks.Task<double> MilesToKMAsync(double d1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SOAP_Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SOAP_Client.ServiceReference1.IService1>, SOAP_Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Greet(string s1, string s2) {
            return base.Channel.Greet(s1, s2);
        }
        
        public System.Threading.Tasks.Task<string> GreetAsync(string s1, string s2) {
            return base.Channel.GreetAsync(s1, s2);
        }
        
        public double MilesToKM(double d1) {
            return base.Channel.MilesToKM(d1);
        }
        
        public System.Threading.Tasks.Task<double> MilesToKMAsync(double d1) {
            return base.Channel.MilesToKMAsync(d1);
        }
    }
}
